// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxakupxcslpgsfgrikss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94YWt1cHhjc2xwZ3NmZ3Jpa3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjM0MTMsImV4cCI6MjA3MDYzOTQxM30.Yn7gTMxiU8W0auTKle411r7WFWIJT8B1_0nVA__UaW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});